INSERT INTO tb_category(name, email, created_At) VALUES ('BOOKS', 'books@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('ELECTRONICS', 'elec@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('COMPUTERS', 'comp@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('BOOKS', 'books@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('ELECTRONICS', 'elec@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('COMPUTERS', 'comp@gmail.com', NOW());INSERT INTO tb_category(name, email, created_At) VALUES ('BOOKS', 'books@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('ELECTRONICS', 'elec@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('COMPUTERS', 'comp@gmail.com', NOW());INSERT INTO tb_category(name, email, created_At) VALUES ('BOOKS', 'books@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('ELECTRONICS', 'elec@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('COMPUTERS', 'comp@gmail.com', NOW());INSERT INTO tb_category(name, email, created_At) VALUES ('BOOKS', 'books@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('ELECTRONICS', 'elec@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('COMPUTERS', 'comp@gmail.com', NOW());INSERT INTO tb_category(name, email, created_At) VALUES ('BOOKS', 'books@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('ELECTRONICS', 'elec@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('COMPUTERS', 'comp@gmail.com', NOW());INSERT INTO tb_category(name, email, created_At) VALUES ('BOOKS', 'books@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('ELECTRONICS', 'elec@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('COMPUTERS', 'comp@gmail.com', NOW());INSERT INTO tb_category(name, email, created_At) VALUES ('BOOKS', 'books@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('ELECTRONICS', 'elec@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('COMPUTERS', 'comp@gmail.com', NOW());INSERT INTO tb_category(name, email, created_At) VALUES ('BOOKS', 'books@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('ELECTRONICS', 'elec@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('COMPUTERS', 'comp@gmail.com', NOW());INSERT INTO tb_category(name, email, created_At) VALUES ('BOOKS', 'books@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('ELECTRONICS', 'elec@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('COMPUTERS', 'comp@gmail.com', NOW());INSERT INTO tb_category(name, email, created_At) VALUES ('BOOKS', 'books@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('ELECTRONICS', 'elec@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('COMPUTERS', 'comp@gmail.com', NOW());INSERT INTO tb_category(name, email, created_At) VALUES ('BOOKS', 'books@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('ELECTRONICS', 'elec@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('COMPUTERS', 'comp@gmail.com', NOW());INSERT INTO tb_category(name, email, created_At) VALUES ('BOOKS', 'books@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('ELECTRONICS', 'elec@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('COMPUTERS', 'comp@gmail.com', NOW());INSERT INTO tb_category(name, email, created_At) VALUES ('BOOKS', 'books@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('ELECTRONICS', 'elec@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('COMPUTERS', 'comp@gmail.com', NOW());INSERT INTO tb_category(name, email, created_At) VALUES ('BOOKS', 'books@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('ELECTRONICS', 'elec@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('COMPUTERS', 'comp@gmail.com', NOW());INSERT INTO tb_category(name, email, created_At) VALUES ('BOOKS', 'books@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('ELECTRONICS', 'elec@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('COMPUTERS', 'comp@gmail.com', NOW());INSERT INTO tb_category(name, email, created_At) VALUES ('BOOKS', 'books@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('ELECTRONICS', 'elec@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('COMPUTERS', 'comp@gmail.com', NOW());INSERT INTO tb_category(name, email, created_At) VALUES ('BOOKS', 'books@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('ELECTRONICS', 'elec@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('COMPUTERS', 'comp@gmail.com', NOW());INSERT INTO tb_category(name, email, created_At) VALUES ('BOOKS', 'books@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('ELECTRONICS', 'elec@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('COMPUTERS', 'comp@gmail.com', NOW());INSERT INTO tb_category(name, email, created_At) VALUES ('BOOKS', 'books@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('ELECTRONICS', 'elec@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('COMPUTERS', 'comp@gmail.com', NOW());INSERT INTO tb_category(name, email, created_At) VALUES ('BOOKS', 'books@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('ELECTRONICS', 'elec@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('COMPUTERS', 'comp@gmail.com', NOW());INSERT INTO tb_category(name, email, created_At) VALUES ('BOOKS', 'books@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('ELECTRONICS', 'elec@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('COMPUTERS', 'comp@gmail.com', NOW());INSERT INTO tb_category(name, email, created_At) VALUES ('BOOKS', 'books@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('ELECTRONICS', 'elec@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('COMPUTERS', 'comp@gmail.com', NOW());INSERT INTO tb_category(name, email, created_At) VALUES ('BOOKS', 'books@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('ELECTRONICS', 'elec@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('COMPUTERS', 'comp@gmail.com', NOW());INSERT INTO tb_category(name, email, created_At) VALUES ('BOOKS', 'books@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('ELECTRONICS', 'elec@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('COMPUTERS', 'comp@gmail.com', NOW());INSERT INTO tb_category(name, email, created_At) VALUES ('BOOKS', 'books@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('ELECTRONICS', 'elec@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('COMPUTERS', 'comp@gmail.com', NOW());INSERT INTO tb_category(name, email, created_At) VALUES ('BOOKS', 'books@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('ELECTRONICS', 'elec@gmail.com', NOW());
INSERT INTO tb_category(name, email, created_At) VALUES ('COMPUTERS', 'comp@gmail.com', NOW());